import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Helmet } from 'react-helmet-async';

export default function WebinarVSLPage() {
        const [viewers, setViewers] = useState(247);

  useEffect(() => {
            const interval = setInterval(() => {
                        setViewers(prev => {
                                      const change = Math.floor(Math.random() * 5) - 2;
                                      const next = prev + change;
                                      return next < 220 ? 220 : next > 280 ? 280 : next;
                        });
            }, 5000);
            return () => clearInterval(interval);
  }, []);

  return (
            < >
                  < Helmet>
                          < title>Exclusive Overview | KenjiAI< /title>
                                  < meta name="robots" content="noindex, nofollow" />
                                < /Helmet>
                                
                                      < div className="min-h-screen bg-[#0B0E14] text-white flex justify-center py-12 px-4 font-sans">
                                              < div className="w-full max-w-4xl">

                                                                < div className="flex flex-col sm:flex-row items-center justify-between bg-[#111822]/80 border border-white/10 backdrop-blur-md px-6 py-4 rounded-t-2xl">
                                                                            < div className="text-center sm:text-left mb-4 sm:mb-0">
                                                                                          < span className="text-blue-500 text-xs font-extrabold uppercase tracking-widest block mb-1">Exclusive Briefing< /span>
                                                                                                        < h1 className="text-lg sm:text-xl font-bold tracking-tight">How To Automate Leads & Scale Without More Work< /h1>
                                                                                                                    < /div>
                                                                                                                    
                                                                                                                                < div className="flex items-center gap-3 bg-red-500/10 border border-red-500/30 px-4 py-2 rounded-full h-fit">
                                                                                                                                              < div className="w-2.5 h-2.5 bg-red-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(239,68,68,0.8)]" />
                                                                                                                                              < div className="font-semibold text-sm tracking-wide">Live: < span className="font-mono">{viewers}< /span>< /div>
                                                                                                                                                          < /div>
                                                                                                                                                                    < /div>
                                                                                                                                                                    
                                                                                                                                                                              < div className="relative bg-[#111822]/40 border-x border-white/10 aspect-video w-full overflow-hidden group">
                                                                                                                                                                                          < iframe
                                                                                                                                                                                                                src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&mute=1&controls=0&rel=0&modestbranding=1"
                                                                                                                                                                                                                className="absolute inset-0 w-full h-full object-cover scale-[1.01]"
                                                                                                                                                                                                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                                                                                                                                                                                                allowFullScreen
                                                                                                                                                                                                              />< /div>
                                                                                                                                                                                                              
                                                                                                                                                                                                                        < div className="bg-[#111822]/80 border border-white/10 backdrop-blur-md px-8 py-10 rounded-b-2xl text-center space-y-8">
                                                                                                                                                                                                                                    < div className="max-w-2xl mx-auto space-y-4">
                                                                                                                                                                                                                                                  < h2 className="text-2xl sm:text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60">
                                                                                                                                                                                                                                                                  Ready to transform your business with AI?
                                                                                                                                                                                                                                                                < /h2>
                                                                                                                                                                                                                                                                              < p className="text-gray-400 text-lg leading-relaxed">
                                                                                                                                                                                                                                                                                              Join 500+ forward-thinking founders who have automated their lead generation and operations.
                                                                                                                                                                                                                                                                                            < /p>
                                                                                                                                                                                                                                                                                                        < /div>
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                    < div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                                                                                                                                                                                                                                                                                                                                  < a
                                                                                                                                                                                                                                                                                                                                                          href="https://calendly.com/kenjiai"
                                                                                                                                                                                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                          className="w-full sm:w-auto px-8 py-4 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl transition-all duration-300 transform hover:scale-105 hover:shadow-[0_0_20px_rgba(37,99,235,0.4)]"
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                  Book Your Strategy Call
                                                                                                                                                                                                                                                                                                                                                < /a>
                                                                                                                                                                                                                                                                                                                                                              < span className="text-gray-500 text-sm font-medium">Limited spots available this week< /span>
                                                                                                                                                                                                                                                                                                                                                                          < /div>
                                                                                                                                                                                                                                                                                                                                                                                    < /div>
                                                                                                                                                                                                                                                                                                                                                                                            < /div>
                                                                                                                                                                                                                                                                                                                                                                                                  < /div>
                                                                                                                                                                                                                                                                                                                                                                                                      < />
                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                < div className="flex flex-col sm:flex-row items-center justify-between bg-[#111822]/80 border border-white/10 backdrop-blur-md px-6 py-4 rounded-t-2xl">
                                                                            < div className="text-center sm:text-left mb-4 sm:mb-0">
                                                                                          < span className="text-blue-500 text-xs font-extrabold uppercase tracking-widest block mb-1">Exclusive Briefing< /span>
                                                                                                        < h1 className="text-lg sm:text-xl font-bold tracking-tight">How To Automate Leads & Scale Without More Work< /h1>
                                                                                                                    < /div>
                                                                                                                    
                                                                                                                                < div className="flex items-center gap-3 bg-red-500/10 border border-red-500/30 px-4 py-2 rounded-full h-fit">
                                                                                                                                              < div className="w-2.5 h-2.5 bg-red-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(239,68,68,0.8)]" />
                                                                                                                                              < div className="font-semibold text-sm tracking-wide">Live: < span className="font-mono">{viewers}< /span>< /div>
                                                                                                                                                          < /div>
                                                                                                                                                                    < /div>
                                                                                                                                                                    
                                                                                                                                                                              < div className="relative bg-[#111822]/40 border-x border-white/10 aspect-video w-full overflow-hidden group">
                                                                                                                                                                                          < iframe
                                                                                                                                                                                                                src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&mute=1&controls=0&rel=0&modestbranding=1"
                                                                                                                                                                                                                className="absolute inset-0 w-full h-full object-cover scale-[1.01]"
                                                                                                                                                                                                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                                                                                                                                                                                                allowFullScreen
                                                                                                                                                                                                              />< /div>
                                                                                                                                                                                                              
                                                                                                                                                                                                                        < div className="bg-[#111822]/80 border border-white/10 backdrop-blur-md px-8 py-10 rounded-b-2xl text-center space-y-8">
                                                                                                                                                                                                                                    < div className="max-w-2xl mx-auto space-y-4">
                                                                                                                                                                                                                                                  < h2 className="text-2xl sm:text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60">
                                                                                                                                                                                                                                                                  Ready to transform your business with AI?
                                                                                                                                                                                                                                                                < /h2>
                                                                                                                                                                                                                                                                              < p className="text-gray-400 text-lg leading-relaxed">
                                                                                                                                                                                                                                                                                              Join 500+ forward-thinking founders who have automated their lead generation and operations.
                                                                                                                                                                                                                                                                                            < /p>
                                                                                                                                                                                                                                                                                                        < /div>
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                    < div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                                                                                                                                                                                                                                                                                                                                  < a
                                                                                                                                                                                                                                                                                                                                                          href="https://calendly.com/kenjiai"
                                                                                                                                                                                                                                                                                                                                                          target="_blank"
                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                          className="w-full sm:w-auto px-8 py-4 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl transition-all duration-300 transform hover:scale-105 hover:shadow-[0_0_20px_rgba(37,99,235,0.4)]"
                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                  Book Your Strategy Call
                                                                                                                                                                                                                                                                                                                                                < /a>
                                                                                                                                                                                                                                                                                                                                                              < span className="text-gray-500 text-sm font-medium">Limited spots available this week< /span>
                                                                                                                                                                                                                                                                                                                                                                          < /div>
                                                                                                                                                                                                                                                                                                                                                                                    < /div>
                                                                                                                                                                                                                                                                                                                                                                                            < /div>
                                                                                                                                                                                                                                                                                                                                                                                                  < /div>
                                                                                                                                                                                                                                                                                                                                                                                                      < />
                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                        
                                                        < div className="flex flex-col sm:flex-row items-center justify-between bg-[#111822]/80 border border-white/10 backdrop-blur-md px-6 py-4 rounded-t-2xl">
                                                                    < div className="text-center sm:text-left mb-4 sm:mb-0">
                                                                                  < span className="text-blue-500 text-xs font-extrabold uppercase tracking-widest block mb-1">Exclusive Briefing< /span>
                                                                                                < h1 className="text-lg sm:text-xl font-bold tracking-tight">How To Automate Leads & Scale Without More Work< /h1>
                                                                                                            < /div>
                                                                                                            
                                                                                                                        < div className="flex items-center gap-3 bg-red-500/10 border border-red-500/30 px-4 py-2 rounded-full h-fit">
                                                                                                                                      < div className="w-2.5 h-2.5 bg-red-500 rounded-full animate-pulse shadow-[0_0_10px_rgba(239,68,68,0.8)]" />
                                                                                                                                      < div className="font-semibold text-sm tracking-wide">Live: < span className="font-mono">{viewers}< /span>< /div>
                                                                                                                                                  < /div>
                                                                                                                                                            < /div>
                                                                                                                                                            
                                                                                                                                                                      < div className="relative bg-[#111822]/40 border-x border-white/10 aspect-video w-full overflow-hidden group">
                                                                                                                                                                                  < iframe
                                                                                                                                                                                                      src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&mute=1&controls=0&rel=0&modestbranding=1"
                                                                                                                                                                                                      className="absolute inset-0 w-full h-full object-cover scale-[1.01]"
                                                                                                                                                                                                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                                                                                                                                                                                      allowFullScreen
                                                                                                                                                                                                    />< /div>
                                                                                                                                                                                                    
                                                                                                                                                                                                              < div className="bg-[#111822]/80 border border-white/10 backdrop-blur-md px-8 py-10 rounded-b-2xl text-center space-y-8">
                                                                                                                                                                                                                          < div className="max-w-2xl mx-auto space-y-4">
                                                                                                                                                                                                                                        < h2 className="text-2xl sm:text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-white/60">
                                                                                                                                                                                                                                                        Ready to transform your business with AI?
                                                                                                                                                                                                                                                      < /h2>
                                                                                                                                                                                                                                                                    < p className="text-gray-400 text-lg leading-relaxed">
                                                                                                                                                                                                                                                                                    Join 500+ forward-thinking founders who have automated their lead generation and operations.
                                                                                                                                                                                                                                                                                  < /p>
                                                                                                                                                                                                                                                                                              < /div>
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                          < div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                                                                                                                                                                                                                                                                                                                        < a
                                                                                                                                                                                                                                                                                                                                              href="https://calendly.com/kenjiai"
                                                                                                                                                                                                                                                                                                                                              target="_blank"
                                                                                                                                                                                                                                                                                                                                              rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                              className="w-full sm:w-auto px-8 py-4 bg-blue-600 hover:bg-blue-500 text-white font-bold rounded-xl transition-all duration-300 transform hover:scale-105 hover:shadow-[0_0_20px_rgba(37,99,235,0.4)]"
                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                        Book Your Strategy Call
                                                                                                                                                                                                                                                                                                                                      < /a>
                                                                                                                                                                                                                                                                                                                                                    < span className="text-gray-500 text-sm font-medium">Limited spots available this week< /span>
                                                                                                                                                                                                                                                                                                                                                                < /div>
                                                                                                                                                                                                                                                                                                                                                                          < /div>
                                                                                                                                                                                                                                                                                                                                                                                  < /div>
                                                                                                                                                                                                                                                                                                                                                                                        < /div>
                                                                                                                                                                                                                                                                                                                                                                                            < />
                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            </>
